### ISSUE TITLE
Wrong computation of fullRange when using a non default rSense valule

### ISSUE THREAD

**Issue by ScholliYT** [MacroYau/LTC2942-Arduino-Library#3]
I am using a `20 mOhm` resitor for rSense and therefore set `_rSense=20`. Wondering why I am getting weird values for the remaining capacity, I found that the computation of the `fullRange` might be wrong.

https://github.com/MacroYau/LTC2942-Arduino-Library/blob/4d6cbaca4a23a1fd689d7a75c9683a0a4abac97e/src/LTC2942.cpp#L68

From my understanding the computation of fullRange is needed to get the offset because a `acr` value of `0xFFFF` should equal `_batteryCapacity` in reality (because `setBatteryToFull()` sets the register to `0xFFFF` independent from the value of `_batteryCapacity`). I suppose to change the line to the following one which actually computes q_lsb and multiplies it with `2^16 = 0xFFFF`. 

```c
float fullRange = 65536 * ((float) _prescalerM / 128) * 0.085 * ((float) 50 / _rSense);
```

what do you think @MacroYau, did you use a resistor other than `50 mOhm` before?

**Comment by MacroYau** [comment]
Good catch! I have only used the LTC2941/2-1 with built-in 50 mΩ sense resistor, so I totally missed this part. Thanks for fixing this!
