### ISSUE TITLE
Wrong value for fullRange in getRemainingCapacity()

### ISSUE THREAD

**Issue by ScholliYT** [MacroYau/LTC2942-Arduino-Library#6]
The max Value here is (or should be) `0xFF = 65535` not `65536` which offsets this by 1 lsb.

https://github.com/MacroYau/LTC2942-Arduino-Library/blob/df80a0b01f0b84be52539b28846826c3feef45b6/src/LTC2942.cpp#L68

**Comment by MacroYau** [comment]
Thanks for catching this! Just released v1.2.2 to fix it.
